---
- hosts: localhost
  connection: local
  gather_facts: True
  vars:
  vars_files:
    - ["vars/main.yml"]
  roles:
    - role: aws-launch-instance

- hosts: LaunchedNode
  roles: 
    - role: common
    - role: jetty

- hosts: localhost
  connection: local
  gather_facts: True
  vars:
  vars_files:
    - ["vars/main.yml"]
  roles:
    - role: create-ami
    - role: create-application-elb
    - role: launch-configuration
    - role: create-cli-autoscaling 
