---
- name: create autoscaling group
  shell: aws autoscaling create-auto-scaling-group --auto-scaling-group-name {{ autoscaling_group_name }} --launch-configuration-name {{ launch_configuration_name }} --min-size {{ min_size }} --max-size {{ max_size }} --desired-capacity {{ desired_capacity }} --target-group-arns {{ target_group_arn }} --availability-zones {{ availability_zones }} --health-check-grace-period 300
  register: auto

- debug: var=auto
