---
- name: "creating ec2 instance"
  ec2:
    key_name: "{{ key_pair }}"
    instance_type: "{{ instance_size }}"
    region: us-west-2
    image: "{{ ami_id }}"
    wait: yes
    group: "{{ sg_name }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      Name: "{{ instance_name }}"
      Stack: "{{ stack_name }}"
    exact_count: 1
    count_tag:
      Name: "{{ instance_name }}"
  register: ec2
- debug: var=ec2.tagged_instances[0].public_ip

- name: Wait for SSH
  local_action: wait_for
                host={{ ec2.tagged_instances[0].public_ip }}
                port=22
                state=started
  #with_items: ec2.tagged_instances[0]
- pause:
    minutes: 1
- name: Add new instance to host group
  local_action: lineinfile
                dest="./hosts"
                regexp={{ ec2.tagged_instances[0].public_ip }}
                insertafter="[LaunchedNode]" line="{{ ec2.tagged_instances[0].public_ip }} ansible_ssh_user=ubuntu  instance_id={{ ec2.tagged_instances[0].id }} ansible_ssh_private_key_file=/home/ubuntu/{{ key_pair }}.pem"
  #with_items: ec2.tagged_instances[0]

- name: insert/update instance_id to vars
  lineinfile:
    dest: /root/ansible/vars/main.yml
    regexp: '^instance_id:'
    line: 'instance_id: {{ ec2.tagged_instances[0].id }}'
  #with_items: ec2.tagged_instances[0]
